# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.0
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-05-29T02:09:47Z"
  labels:
    app: v2ray
  name: v2ray
spec:
  containers:
  - env:
    - name: v2ray.vmess.aead.forced
      value: "false"
    image: ghcr.io/getimages/v2fly-core:v4.45.2
    name: v2ray-server
    ports:
    - containerPort: 80
      hostPort: 80
    - containerPort: 443
      hostPort: 443
    volumeMounts:
    - mountPath: /etc/v2ray/
      name: opt-podman-v2ray-v2ray-caddy-cdn-v2ray-config-host-0
    - mountPath: /var/log/v2ray/
      name: opt-podman-v2ray-v2ray-caddy-cdn-v2ray-logs-host-1
  - image: ghcr.io/getimages/caddy:2.6.2-alpine
    name: v2ray-caddy
    volumeMounts:
    - mountPath: /etc/caddy/Caddyfile
      name: opt-podman-v2ray-v2ray-caddy-cdn-caddy-Caddyfile-host-0
    - mountPath: /usr/share/caddy
      name: opt-podman-v2ray-v2ray-caddy-cdn-caddy-web-host-1
    - mountPath: /data/caddy/
      name: opt-podman-v2ray-v2ray-caddy-cdn-caddy-data-host-2
    - mountPath: /config/caddy
      name: opt-podman-v2ray-v2ray-caddy-cdn-caddy-config-host-3
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /opt/podman/v2ray/v2ray-caddy-cdn/caddy/Caddyfile
      type: File
    name: opt-podman-v2ray-v2ray-caddy-cdn-caddy-Caddyfile-host-0
  - hostPath:
      path: /opt/podman/v2ray/v2ray-caddy-cdn/caddy/web
      type: Directory
    name: opt-podman-v2ray-v2ray-caddy-cdn-caddy-web-host-1
  - hostPath:
      path: /opt/podman/v2ray/v2ray-caddy-cdn/caddy/data
      type: Directory
    name: opt-podman-v2ray-v2ray-caddy-cdn-caddy-data-host-2
  - hostPath:
      path: /opt/podman/v2ray/v2ray-caddy-cdn/caddy/config
      type: Directory
    name: opt-podman-v2ray-v2ray-caddy-cdn-caddy-config-host-3
  - hostPath:
      path: /opt/podman/v2ray/v2ray-caddy-cdn/v2ray/config
      type: Directory
    name: opt-podman-v2ray-v2ray-caddy-cdn-v2ray-config-host-0
  - hostPath:
      path: /opt/podman/v2ray/v2ray-caddy-cdn/v2ray/logs
      type: Directory
    name: opt-podman-v2ray-v2ray-caddy-cdn-v2ray-logs-host-1

